# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_text', models.CharField(max_length=100)),
                ('foreign_text', models.CharField(max_length=100)),
                ('description_text', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('last_date', models.DateTimeField(verbose_name='date last showed')),
            ],
        ),
    ]
